# Scaffolding generated by Caseadilla 0.0.6

module Caseadilla
  class PeopleController < Caseadilla::CaseadillaController
  
    ## optional filters for defining usage according to Caseadilla::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @caseadilla_page_title = 'People'
  		@people = Person.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @caseadilla_page_title = 'View person'
      @person = Person.find params[:id]
      @person.time_slots.build
    end
  
    def new
      @caseadilla_page_title = 'Add a new person'
    	@person = Person.new
      @params = params
      unless params['day'].nil? && params['time'].nil?
        @person.time_slots.build day: params['day'], time: (DateTime.parse(params['time']) - 1.hour)
      else
        @person.time_slots.build
      end
    end

    def create
      params = person_params
      @person = Person.new person_params
    
      if @person.save
        flash[:notice] = 'Person created'
        redirect_to caseadilla_root_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new person'
        render :action => :new
      end
    end
  
    def update
      @caseadilla_page_title = 'Update person'
      
      @person = Person.find params[:id]
    
      if @person.update_attributes person_params
        flash[:notice] = 'Person has been updated'
        redirect_to caseadilla_root_path
      else
        flash.now[:warning] = 'There were problems when trying to update this person'
        render :action => :show
      end
    end
 
    def destroy
      @person = Person.find params[:id]

      @person.destroy
      flash[:notice] = 'Person has been deleted'
      redirect_to caseadilla_people_path
    end
  
    private
      
      def person_params
        params.require(:person).permit(:name, :email, :time, time_slots_attributes: [:time, :day, :id], reminder_ids: [])
      end

  end
end