# Scaffolding generated by Caseadilla 0.0.6

module Caseadilla
  class RemindersController < Caseadilla::CaseadillaController
  
    ## optional filters for defining usage according to Caseadilla::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @caseadilla_page_title = 'Reminders'
  		@reminders = Reminder.order(sort_order(:hours_before)).paginate :page => params[:page]
    end
  
    def show
      @caseadilla_page_title = 'View reminder'
      @reminder = Reminder.find params[:id]
    end
  
    def new
      @caseadilla_page_title = 'Add a new reminder'
    	@reminder = Reminder.new
    end

    def create
      @reminder = Reminder.new reminder_params
    
      if @reminder.save
        flash[:notice] = 'Reminder created'
        redirect_to caseadilla_reminders_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new reminder'
        render :action => :new
      end
    end
  
    def update
      @caseadilla_page_title = 'Update reminder'
      
      @reminder = Reminder.find params[:id]
    
      if @reminder.update_attributes reminder_params
        flash[:notice] = 'Reminder has been updated'
        redirect_to caseadilla_reminders_path
      else
        flash.now[:warning] = 'There were problems when trying to update this reminder'
        render :action => :show
      end
    end
 
    def destroy
      @reminder = Reminder.find params[:id]

      @reminder.destroy
      flash[:notice] = 'Reminder has been deleted'
      redirect_to caseadilla_reminders_path
    end
  
    private
      
      def reminder_params
        params.require(:reminder).permit(:hours_before, :message)
      end

  end
end